# Generated by Django 4.2.1 on 2023-05-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_postmodel_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='dateposted',
            new_name='date_posted',
        ),
    ]
